from datetime import datetime, date, time, timedelta
# https://docs.python.org/3/library/datetime.html

print(f"datetime(year, month, day, hour, minute, second, microsecond[, tzinfo]) - {datetime(2000, 5, 28, 8, 30, 10, 15)}")
print("---"*20)
print(f"date(year, month, day) - {date(2000, 5, 28)}")
print("---"*20)
print(f"time(hour, minute, second, microsecond[, tzinfo]) - {time(8, 30, 10, 15)}")
print("---"*20)
print("timedelta(days, seconds, microseconds, milliseconds, minutes, hours, weeks)")
delta = timedelta(days=10, hours=8, minutes=12)
print(delta)
print("---"*20)
print(f"delta.total_seconds() - {delta.total_seconds()}")
print("---"*20)
start = date(2000, 5, 28)
end = date(2020, 1, 1)
print(end, start)
print(f"end - start -> {end - start}")
print("---"*20)
print(f"start.year - {start.year}")
print(f"start.month - {start.month}")
print(f"start.day - {start.day}")
print("---"*20)
example_date = datetime(2000, 5, 28, 8, 30, 10, 15)
print(f"example_date + delta -> {example_date + delta}")
print("---"*20)
print(f"date.today() - {date.today()}")
print("---"*20)
print(f"datetime.now() - {datetime.now()}")
print("---"*20)
